config/routes.rb
Rails.application.routes.draw do
  
devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :zones
  resources :comments

  devise_for :managers

  get '/search' => 'pages#search', :as => 'search_page'
  
  resources :liners
  resources :deliveries
  resources :transits
  resources :orders
  resources :line_items

  resources :line_items do
    get 'decrease', on: :member
    get 'increase', on: :member
  end

  resources :carts
  

  root 'home#index'
  resources :home
  resources :articles

   resources :articles, only: [:show] do
     resources :pictures, only: [:create]
  end

    resources :articles do
      resources :comments
    end
  resources :types
  resources :products
  resources :products do
    resources :likes
  end
  resources :charges
  resources :users

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
     has_one_attached :picture
    
    has_many :Products
    has_many :types, through: :Products

    has_many :comments, dependent: :destroy

   
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :line_items

    # def add_products(product)
    #     item = line_items.find_by(product: product)

    #     if item
    #         item.quantity += 1
    #     else
    #         item = line_items.new(product: product)
    #     end

    # end

    def add_products(product, current_user = nil)
      # make sure your Item class initializes quantity to o, not nil.
      current_item = line_items.find_or_initialize_by(product: product)

      current_item.increment!(:quantity)
      current_item.user = current_user
      current_item.product.save
      current_item
    end

    def total
        line_items.to_a.sum(&:total)
    end

    # def tax
    #     (line_items.to_a.sum(&:total) *10 ) /100 
    # end

    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item
        current_item.quantity += 1
        else
        current_item = line_items.build(product_id: product.id)
        end
        current_item
    end

  def remove_product(product)
    
    current_item = line_items.find_by(product_id: product.id)

    if current_item.quantity > 1
      current_item.quantity -= 1
    elsif current_item.quantity = 1
      current_item.destroy
    end
    current_item
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :body, presence: true, allow_blank: false
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :user
  has_many :liners, dependent: :destroy

    def restreint_transit(transit, order)
      item = liners.find_by(transit: transit, order: order)

      if item
        item
      else
        item = liners.new(transit: transit, order: order)
      end

      item
    end


    def total
      liners.to_a.sum(&:total)
    end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  belongs_to :user

  def total
    product.price * quantity
  end
end

app/models/liner.rb
class Liner < ApplicationRecord
  belongs_to :delivery
  belongs_to :transit

  belongs_to :order

  def total
    # if order.zone_id = 1...5
    #   transit.price+100
    # elsif order.zone_id = 6...9
    #   transit.price+200
    # end
      
    case order.zone_id
    when 1..5
      transit.price+10
    when 6..9
      transit.price+100
    when 10..31
      transit.price+1000
    else
      
    end
  end
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :cart
  belongs_to :zone
  belongs_to :user

  has_many :liners

  enum status: [:ordered, :payed, :in_progress, :sent]

  validates :name, :address, :email, presence: true
  validates :status, inclusion: statuses.keys

  def order_send
    OrderMailer.order_email(self).deliver_now
  end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :type
    belongs_to :article

    has_many :line_items, dependent: :nullify
    has_many :likes, dependent: :destroy
end

app/models/transit.rb
class Transit < ApplicationRecord
  has_many :liners, dependent: :destroy
end
 

app/models/type.rb
class Type < ApplicationRecord
    has_many :products
    has_many :articles, through: :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :welcome_send
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  devise :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_one :cart
  has_one :delivery
  has_one_attached :avatar

  has_many :orders
  has_many :line_items
  has_many :comments, dependent: :destroy



  
  def self.from_facebook(auth)
    where(facebook_id: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.username = auth.info.name 
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end

  # def self.from_omniauth(access_token)
  #   data = access_token.info
  #   user = User.where(email: data['email']).first
  #   # Uncomment the section below if you want users to be created if they don't exist
  #   unless user
  #       user = User.create(name: data['name'],
  #          email: data['email'],
  #          password: Devise.friendly_token[0,20]
  #       )
  #   end
  #   user
  # end

  def self.from_omniauth(auth)
    where(google_id: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.username = auth.info.name 
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end


  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end 
end

app/models/zone.rb
class Zone < ApplicationRecord
  has_many :orders
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :show, :update]
    before_action :authenticate_manager!, only: [:create, :edit, :update, :destroy]

    def index
        @article = Article.all
          
    end

    def new
        @article = Article.new
        # @articl = @article.find(params[:id])
    end

    def create
        article_params = params.require(:article).permit(:title, :season, :description, :image_url, :origin, :picture)
       @article = Article.create(article_params)
       redirect_to root_path
    end

    def edit
    end

    def update
        article_params = params.require(:article).permit(:title, :season, :description, :image_url, :origin, :picture)
        @article.update(article_params)
        redirect_to root_path
    end

    def show
        @articlee = Article.all
        @articlee = @articlee[0..2]

        @comment = Comment.new
        @commente = @article.comments.order(created_at: :desc)
        @comments = @commente[0..2]

        if @article.comments.blank?
            @average_comment = 0
        else
            @average_comment = @article.comments.average(:rating).round(2)
        end


        # respond_to do |format|
        #     format.js { render inline: "location.reload();" }
        # end
    
    end

    def destroy
        @articl = Article.find(params[:id])
        @articl.destroy
        redirect_to root_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/articles/_raty.html.erb
<div class="average-review-rating" data-score=<%= @average_comment%>>
  <span class="btn btn-success btnvert sm"><%= @average_comment%></span>
  </div>


<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function () {
      return $(this).attr('data-score')
    }
  })
</script>

app/views/articles/create.html.erb
page create ty

app/views/articles/edit.html.erb
<div class="container">

 <%=form_for @article,url:{action:"update"} do |f|%>
  <div class="form-row">
    <div class="col-md-4 mb-3">
      <%# <label for="validationDefault01">First name</label> %>
      <%= f.label :title, "Titre", for:"validationDefault01"  %>
      <%# <input type="text" class="form-control" id="validationDefault01" placeholder="First name" value="Mark" required> %>
      <%=f.text_field :title, placeholder: "Titre",class: "form-control", id:"validationDefault01"%>
    </div>
    <div class="col-md-4 mb-3">
      <%# <label for="validationDefault02">Last name</label> %>
       <%= f.label :season, "Saison", for:"validationDefault02"  %>
      <%# <input type="text" class="form-control" id="validationDefault02" placeholder="Last name" value="Otto" required> %>
      <%=f.text_field :season, placeholder: "Saison",class: "form-control", id:"validationDefault02"%>
    </div>
     <div class="col-md-4 mb-3">
      <%# <label for="validationDefault02">Last name</label> %>
       <%= f.label :origin, "Origine", for:"validationDefault03"  %>
      <%# <input type="text" class="form-control" id="validationDefault02" placeholder="Last name" value="Otto" required> %>
      <%=f.text_field :origin, placeholder: "Origine",class: "form-control", id:"validationDefault03"%>
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-6 mb-3">
        <div class="form-group">
          <%# <label for="exampleFormControlTextarea1">Example textarea</label> %>
          <%= f.label :description, "Description", for:"exampleFormControlTextarea1"  %>
          <%# <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea> %>
           <%=f.text_area :description, placeholder: "Description",class: "form-control", id:"exampleFormControlTextarea1", rows:"3"%>
      </div>
    </div>
   <div class="field">
     <%= f.label :picture %>
     <%= f.file_field :picture %>
   </div>
  </div>
  <div class="form-group">
   <%= f.submit 'valider', class:"btn btn-primary"%>
  </div>
<%end%>
</div>

app/views/articles/index.html.erb
<div class="container marketing">
  <div>
    <h2 class="center">Nos produits </h2>
    <%= image_tag "ligne1.png", class:"ligneimage"%>
  </div>





  <div class="row">
    <%# debut de l'article %>
    <% @article.each do |article|%>
    <%# lien modal %>
    <%if current_manager %>
    <div class="col-lg-4">
      <%= link_to home_path(article.id), remote: true do %>
      <% if article.picture.attached? %>
      <%= image_tag (article.picture), class:"rounded-circle tailimgmanager"%>
      <%else%>
      <%= image_tag (article.image_url), class:"rounded-circle tailimgmanager" %>
      <%end%>
      <%end%>

      <h2><%= article.title %></h2>
      <%= article.id%>
      <!-- <div class="taildiv">
              <p class="tailsp"><%= article.description%></p>
              </div> -->
      <a href="articles/<%=article.id%>/edit"> <i class="far fa-edit"></i></a>
      <a href="articles/<%=article.id%>" data-method="delete" , data-confirm="are you sur?"><i
          class="far fa-trash-alt"></i></a>
      <a href="articles/<%=article.id%>"> <i class="far fa-eye"></i></i></a>
      <a href="<%= article_comments_path(article)%>">
        <p>(<%= pluralize(article.comments.count, "Avi") %>)</p>
      </a>
    </div>
    <% else %>
    <div class="col-sm-4 spacemarg">
      <div class="containere">
        <a href="articles/<%=article.id%>">
          <% if article.picture.attached? %>
          <%= image_tag (article.picture), class:"tail"%>
          <%else%>
          <%= image_tag (article.image_url), class:"tail" %>
          <%end%>
        </a>
        <div class="cont">
          <p class="center"><%= article.title %></p>
          <div class="overlay">
            <div class="text">
              <div class="taildiv tailsp">
                <% link_to home_path(article.id), remote: true do %>
                <i class="far fa-plus-square  iconcolor"></i>
                <%end%>
              </div>
              <%= link_to home_path(article.id), remote: true do %>
              <p class="btn btn-success btnvert">Acheter</p>
              <%end%>

            </div>
          </div>
        </div>
        <div>
          <p class="center topavis">

            <span class="noteavis">
              <%if article.comments.blank?%>
              <%= average_comment = 0%>
              <%else%>
              <%= average_comment = article.comments.average(:rating).round(2)%>
              <%end%>
            </span>
            <span style="color: rgb(239, 184, 3);">
              <i class="fas fa-star"></i>
            </span>

            (<a href="<%= article_comments_path(article)%>" , class="coloravis">
              <%= pluralize(article.comments.count, "Avi") %>
            </a>)
          </p>
        </div>
      </div>
    </div>
    <%end%>
    <%end%>
  </div>
</div>
<div id='post-content'></div>

app/views/articles/new.html.erb
<div class="container">

 <%=form_for @article,url:{action:"create"} do |f|%>
  <div class="form-row">
    <div class="col-md-4 mb-3">
      <%# <label for="validationDefault01">First name</label> %>
      <%= f.label :title, "Titre", for:"validationDefault01"  %>
      <%# <input type="text" class="form-control" id="validationDefault01" placeholder="First name" value="Mark" required> %>
      <%=f.text_field :title, placeholder: "Titre",class: "form-control", id:"validationDefault01"%>
    </div>
    <div class="col-md-4 mb-3">
      <%# <label for="validationDefault02">Last name</label> %>
       <%= f.label :season, "Saison", for:"validationDefault02"  %>
      <%# <input type="text" class="form-control" id="validationDefault02" placeholder="Last name" value="Otto" required> %>
      <%=f.text_field :season, placeholder: "Saison",class: "form-control", id:"validationDefault02"%>
    </div>
     <div class="col-md-4 mb-3">
      <%# <label for="validationDefault02">Last name</label> %>
       <%= f.label :origin, "Origine", for:"validationDefault03"  %>
      <%# <input type="text" class="form-control" id="validationDefault02" placeholder="Last name" value="Otto" required> %>
      <%=f.text_field :origin, placeholder: "Origine",class: "form-control", id:"validationDefault03"%>
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-6 mb-3">
      <div class="form-group">
        <%# <label for="exampleFormControlTextarea1">Example textarea</label> %>
        <%= f.label :description, "Description", for:"exampleFormControlTextarea1"  %>
        <%# <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea> %>
          <%=f.text_area :description, placeholder: "Description",class: "form-control", id:"exampleFormControlTextarea1", rows:"3"%>
      </div>
      <div class="field">
        <%= f.label :picture %>
        <%= f.file_field :picture %>
      </div>

    </div>
  </div>
  <div class="form-group">
   <%= f.submit 'valider', class:"btn btn-primary"%>
  </div>
<%end%>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 haut">
      <h1 class="my-4">
        <small><%= @article.title%></small>
      </h1>
    <%# if @article.image_url == nil %>
      <%if @article.picture.attached?%>
        <%= image_tag (@article.picture), class:"img-fluid tailimg"%>
      <%else%>
        <% if @article.image_url == nil %>
          <%= image_tag ("fond.jpg"), class:"img-fluid tailimg"%>
        <%else%>
          <%= image_tag (@article.image_url), class:"img-fluid tailimg" %>
        <%end%>
        <%# image_tag (@article.image_url), class:"img-fluid" %>
      <%end%>
      <% if manager_signed_in? %>
        <% if current_user == current_manager %>
          <%= form_tag article_pictures_path(@article), multipart: true do %>
            <%= file_field_tag :picture %>
            <%= submit_tag "mettre à jour" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-6 haut">
      <div class="conditonement">
        <h2>Conditionnement</h2>
        <div class="row">
          <% @article.Products.each do |product| %>
          <div class="col-lg-4 margcondit">
            <%if @article.picture.attached?%>
            <%= image_tag (@article.picture), class:"img-fluid"%>
            <%else%>
            <% if @article.image_url == nil %>
            <%= image_tag ("fond.jpg"), class:"img-fluid"%>
            <%else%>
            <%= image_tag (@article.image_url), class:"img-fluid" %>
            <%end%>
            <%end%>
            <h5><%= product.type.content %></h5>
            <ul>
              <li>
                <%if product.type.content == "Vrac" %>
                <p class="listprod"><%= product.price%> euros/kg</p>
                <%else%>
                <div class="listprod"><%= product.price%> euros/unité</p>
                  <%end%>
              </li>
              <li>
                <%if  product.disponibility == true %>
                <p class="listprod listcol">Disponible </p>
                <%else%>
                <p class="listprod listcol">pas disponible </p>
                <%end%>
              </li>
            </ul>
            
              <div>
                <%= button_to line_items_path(product_id: product.id),class:"btn btn-warning" do %>
                <i class="fas fa-shopping-basket"></i>
                <% end %>
              </div>
          </div>
          <% end %>
        </div>
      </div>
      <hr>

      <!-- avis  -->
      <div id="comment_pane">
        <% @comments.each do |comment|%>
          <%= render "comments/comment", comment: comment%>
        <%end%>
      </div>
      <!-- fin avis -->

    </div>
    <div class="col-md-6">
      <h1 class="my-4">
        <small>Fiche technique </small>
      </h1>
      <ul class="list-group">
          <li class="list-group-item list-group-item-secondary">This is a primary list group item</li>
          <li class="list-group-item ">This is a secondary list group item</li>
          <li class="list-group-item list-group-item-secondary">This is a success list group item</li>
          <li class="list-group-item ">This is a danger list group item</li>
          <li class="list-group-item list-group-item-secondary">This is a warning list group item</li>
          <li class="list-group-item ">This is a info list group item</li>
          <li class="list-group-item list-group-item-secondary">This is a light list group item</li>
          <li class="list-group-item ">This is a dark list group item</li>
      </ul>
    </div>
    <div class="col-md-6">
      <h1 class="my-4">
        <small>Valeurs nutritive</small>
      </h1>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>Larry</td>
            <td>the Bird</td>
            <td>@twitter</td>
          </tr>
        </tbody>
      </table>
      <hr>
     <h1 class="my-4">
       <small>Avis</small>
     </h1>
     <!-- avis global -->
     <div>
       <%=render 'raty.html.erb' %>
     </div>
     <%= link_to "voir tous les avis", article_comments_path(@article)%>
    </div>
  </div>
  <h3 class="my-4">Related Projects</h3>
  <div class="row">
    <% @articlee.each do |article|%>
      <div class="col-md-3 col-sm-6 mb-4">
        <a href="/articles/<%= article.id%>">
          <% if article.image_url == nil %>
            <%= image_tag ("fond.jpg"), class:"img-fluid tailimg"%>
          <%else%>
            <%= image_tag (article.image_url), class:"img-fluid tailimg" %>
          <%end%>
        </a>
      </div>
    <%end%>
  </div>
  <%= link_to 'voir', articles_path, class:"btn btn-outline-primary"%>
</div>

app/views/articles/update.html.erb
page update ty