config/routes.rb
Rails.application.routes.draw do
  
devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :zones
  resources :comments

  devise_for :managers

  get '/search' => 'pages#search', :as => 'search_page'
  
  resources :liners
  resources :deliveries
  resources :transits
  resources :orders
  resources :line_items

  resources :line_items do
    get 'decrease', on: :member
    get 'increase', on: :member
  end

  resources :carts
  

  root 'home#index'
  resources :home
  resources :articles

   resources :articles, only: [:show] do
     resources :pictures, only: [:create]
  end

    resources :articles do
      resources :comments
    end
  resources :types
  resources :products
  resources :products do
    resources :likes
  end
  resources :charges
  resources :users

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/transit.rb
class Transit < ApplicationRecord
  has_many :liners, dependent: :destroy
end
 

app/controllers/transits_controller.rb
class TransitsController < ApplicationController
  include CurrentCart
  include CurrentDelivery
  before_action :set_transit, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_manager!, only: [:create, :edit, :update, :destroy]

  # GET /transits
  # GET /transits.json
  def index
    if current_user.delivery == nil
        @transits = Transit.all
         @cart = Cart.find(current_user.cart.id)
    @liner = Liner.all
     @order = Order.all
     @zones = Zone.all
    else
    @delivery = Delivery.find(current_user.delivery.id)
     @transits = Transit.all
         @cart = Cart.find(current_user.cart.id)
    @liner = Liner.all
     @order = Order.all
     @zones = Zone.all
    end
  end

  # GET /transits/1
  # GET /transits/1.json
  def show
  end

  # GET /transits/new
  def new
    @transit = Transit.new
  end

  # GET /transits/1/edit
  def edit
  end

  # POST /transits
  # POST /transits.json
  def create
    @transit = Transit.new(transit_params)

    respond_to do |format|
      if @transit.save
        format.html { redirect_to @transit, notice: 'Transit was successfully created.' }
        format.json { render :show, status: :created, location: @transit }
      else
        format.html { render :new }
        format.json { render json: @transit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transits/1
  # PATCH/PUT /transits/1.json
  def update
    respond_to do |format|
      if @transit.update(transit_params)
        format.html { redirect_to @transit, notice: 'Transit was successfully updated.' }
        format.json { render :show, status: :ok, location: @transit }
      else
        format.html { render :edit }
        format.json { render json: @transit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transits/1
  # DELETE /transits/1.json
  def destroy
    @transit.destroy
    respond_to do |format|
      format.html { redirect_to transits_url, notice: 'Transit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transit
      @transit = Transit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transit_params
      params.require(:transit).permit(:name, :mode, :price)
    end
end

app/helpers/transits_helper.rb
module TransitsHelper
end

app/views/transits/_form.html.erb
<%= form_with(model: transit, local: true) do |form| %>
  <% if transit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transit.errors.count, "error") %> prohibited this transit from being saved:</h2>

      <ul>
      <% transit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :mode %>
    <%= form.text_field :mode %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transits/edit.html.erb
<h1>Editing Transit</h1>

<%= render 'form', transit: @transit %>

<%= link_to 'Show', @transit %> |
<%= link_to 'Back', transits_path %>

app/views/transits/index.html.erb
<div class="container">
<%= render "/carts/cart.html.erb" %>


<h1>Livraison</h1>



  <div class="row">
    <div class="col">
     <table>
       <thead>
         <tr>
           <th>Name</th>
           <th>Mode</th>
           <th>Price</th>
           <th colspan="3"></th>
         </tr>
       </thead>

       <tbody>
         <% @transits.each do |transit| %>
         <% if transit.mode == "Normal"%>
         <tr>
           <td><%= transit.name %></td>
           <td><%= transit.mode %></td>
           <td><%= transit.price %></td>
           <td><%= link_to 'Show', transit %></td>
           <td><%= link_to 'Edit', edit_transit_path(transit) %></td>
           <td><%= link_to 'Destroy', transit, method: :delete, data: { confirm: 'Are you sure?' } %></td>

          <% if current_user.delivery == nil %>
       
            <td>
              <%= button_to "choisir", liners_path(transit_id: transit, order_id: @order.last), class:"btn btn-outline-primary"%>
            </td>
        
           
           <%else%>
          <%end%>

         </tr>
         <% end %>
         <% end %>
       </tbody>
     </table>
    </div>
    <div class="col">
     <table>
       <thead>
         <tr>
           <th>Name</th>
           <th>Mode</th>
           <th>Price</th>
           <th colspan="3"></th>
         </tr>
       </thead>

       <tbody>
         <% @transits.each do |transit| %>
         <% if transit.mode == "Rapide"%>
         <tr>
           <td><%= transit.name %></td>
           <td><%= transit.mode %></td>
           <td><%= transit.price %></td>
           <td><%= link_to 'Show', transit %></td>
           <td><%= link_to 'Edit', edit_transit_path(transit) %></td>
           <td><%= link_to 'Destroy', transit, method: :delete, data: { confirm: 'Are you sure?' } %></td>

             <% if current_user.delivery == nil %>
             <td>
               <%= button_to "choisir", liners_path(transit_id: transit, order_id: @order.last), class:"btn btn-outline-primary"%>
             </td>
             <%else%>
             <%end%>
         </tr>
         <% end %>
         <% end %>
       </tbody>
     </table>
    </div>
  </div>




<br>

<%= link_to 'New Transit', new_transit_path %>

<br>

<%= render "/deliveries/show.html.erb" %>

 <% if current_user.delivery == nil %>
<br>
 <%else%>
<%= render "/charges/new.html.erb" %>
 <%end%>

</div>

app/views/transits/new.html.erb
<h1>New Transit</h1>

<%= render 'form', transit: @transit %>

<%= link_to 'Back', transits_path %>

app/views/transits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @transit.name %>
</p>

<p>
  <strong>Mode:</strong>
  <%= @transit.mode %>
</p>

<p>
  <strong>Price:</strong>
  <%= @transit.price %>
</p>

<%= link_to 'Edit', edit_transit_path(@transit) %> |
<%= link_to 'Back', transits_path %>