config/routes.rb
Rails.application.routes.draw do
  
devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :zones
  resources :comments

  devise_for :managers

  get '/search' => 'pages#search', :as => 'search_page'
  
  resources :liners
  resources :deliveries
  resources :transits
  resources :orders
  resources :line_items

  resources :line_items do
    get 'decrease', on: :member
    get 'increase', on: :member
  end

  resources :carts
  

  root 'home#index'
  resources :home
  resources :articles

   resources :articles, only: [:show] do
     resources :pictures, only: [:create]
  end

    resources :articles do
      resources :comments
    end
  resources :types
  resources :products
  resources :products do
    resources :likes
  end
  resources :charges
  resources :users

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :line_items

    # def add_products(product)
    #     item = line_items.find_by(product: product)

    #     if item
    #         item.quantity += 1
    #     else
    #         item = line_items.new(product: product)
    #     end

    # end

    def add_products(product, current_user = nil)
      # make sure your Item class initializes quantity to o, not nil.
      current_item = line_items.find_or_initialize_by(product: product)

      current_item.increment!(:quantity)
      current_item.user = current_user
      current_item.product.save
      current_item
    end

    def total
        line_items.to_a.sum(&:total)
    end

    # def tax
    #     (line_items.to_a.sum(&:total) *10 ) /100 
    # end

    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item
        current_item.quantity += 1
        else
        current_item = line_items.build(product_id: product.id)
        end
        current_item
    end

  def remove_product(product)
    
    current_item = line_items.find_by(product_id: product.id)

    if current_item.quantity > 1
      current_item.quantity -= 1
    elsif current_item.quantity = 1
      current_item.destroy
    end
    current_item
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  #  before_action :authenticate_manager!, only: [:edit, :update]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    #  @line_item = LineItem.find(params[:id])
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
  #   @cart.destroy if @cart.id == current_user.cart.id
  # session[:cart_id] = nil
    return unless @cart.id == current_user.cart.id
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def invalid_cart
      redirect_to root_path, alert: "not found"
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">image produit</th>
      <th scope="col">quantité</th>
      <th scope="col">prix</th>
      <th scope="col">supprimer</th>
    </tr>
  </thead>
  <tbody>
  <% @cart.line_items.each do |item|%>
    <tr>
      <td class="spacecol"><%=image_tag (Article.find(item.product.article_id).image_url), class:"imagecolcontent"%></td>
      <td><%= item.quantity%></td>
      <td><%= number_to_currency(item.total, unit:"euro", separator:",", format: "%n %u")%></td>
      <td><a href="/line_items/<%= item.id%>" data-method="delete" data-confirm="êtes vous sure ?" class="badge badge-danger">Enlever du panier</a></td>
    </tr>
     <%end%>
  </tbody>
</table>

<p> total : <span
    class="badge badge-info"><%= number_to_currency(@cart.total, unit:"euro", separator:",", format: "%n %u")%></p>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>Votre panier est vide </h1>

<%# <%= render 'form', cart: @cart %>

<%= link_to 'Back', root_path %>

app/views/carts/show.html.erb
<section>
  <div class="container">
    <table class="table table-responsive">
      <thead class="thead-light">
        <tr>
          <th scope="col">image produit</th>
          <th>Nom et conditionnement </th>
          <th scope="col">quantité</th>
          <th scope="col">prix</th>
          <th scope="col">supprimer</th>
          <th scope="col">Soustotal</th>
  
        </tr>
      </thead>
      <tbody>
        <% @cart.line_items.each do |item|%>
        <tr>
          <td class="spacecol"><%=image_tag (Article.find(item.product.article_id).image_url), class:"imagecolcontent"%>
          </td>
          <td><%= item.product.article.title%> <br> <%= item.product.type.content%> </td>
          <td>
            <div class="input-group qttydiv">
              <div class="input-group-prepend">
                <%= link_to "", decrease_line_item_path(product_id: item.product), class:"fa fa-minus minusbtn btn btn-dark btn-sm" %>
              </div>
              <input class="sizeqty" value="<%= item.quantity%>">
              <div class="input-group-prepend">
                <%= link_to "", increase_line_item_path(product_id: item.product), class:"fa fa-plus minusbtn btn btn-dark btn-sm" %>
              </div>
            </div>
          </td>
          <td><%= item.product.price%> euro</td>
          <td><a href="/line_items/<%= item.id%>" data-method="delete" data-confirm="êtes vous sure ?" class=""><i
                class="fa fa-trash trashbtn"></i></a></td>
          <td><%= number_to_currency(item.total, unit:"euro", separator:",", format: "%n %u")%></td>
        </tr>
        <%end%>
      </tbody>
    </table>
    <div class="totalcart">
      <p> Total : <span
          class="badge badge-info"><%= number_to_currency(@cart.total, unit:"euro", separator:",", format: "%n %u")%></p>
  
      <div>
        <% if @cart.line_items.empty? %>
        <% else %>
        <%= button_to "passer la commande", new_order_path(cart_id: @cart), method: :get, class:"btn btn-primary mb-2"%>
        <% end %>
      </div>
  
    </div>
  
  
    <%# <%= button_to "vider le panier", @cart, method: :delete, data:{confirm:"Êtes vous sûr?"}, class:"btn btn-danger" %>
    <!-- <a href="/carts/<%= current_user.cart.id%>" data-method="delete" data-confirm="êtes vous sure ?" class="badge badge-danger">vider le panier</a> -->
    <a href="/">back</a>
  </div>

</section>
 