config/routes.rb
Rails.application.routes.draw do
  
devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :zones
  resources :comments

  devise_for :managers

  get '/search' => 'pages#search', :as => 'search_page'
  
  resources :liners
  resources :deliveries
  resources :transits
  resources :orders
  resources :line_items

  resources :line_items do
    get 'decrease', on: :member
    get 'increase', on: :member
  end

  resources :carts
  

  root 'home#index'
  resources :home
  resources :articles

   resources :articles, only: [:show] do
     resources :pictures, only: [:create]
  end

    resources :articles do
      resources :comments
    end
  resources :types
  resources :products
  resources :products do
    resources :likes
  end
  resources :charges
  resources :users

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :type
    belongs_to :article

    has_many :line_items, dependent: :nullify
    has_many :likes, dependent: :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   before_action :authenticate_manager!, only: [:create, :update, :destroy]
   before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @product = Product.all
    @article = Article.find_by(params[:id])
    @type = Type.find_by(params[:id])
  end

  def show
    
    @a = @product.type_id
    @typ = Type.find(@a)

    @art = @product.article_id
    @arti = Article.find(@art)

    #  respond_to do |format|
    #   format.js
    # end
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
     @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
     @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Transit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:article_id, :type_id, :price, :disponibility)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
<% if product.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(product.errors.count, "error") %> prohibited this line_item from being saved:</h2>

  <ul>
    <% product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :article_id %>
  <%= form.text_field :article_id %>
</div>

<div class="field">
  <%= form.label :type_id %>
  <%= form.text_field :type_id %>
</div>

<div class="field">
  <%= form.label :price %>
  <%= form.text_field :price %>
</div>

<div class="field">
  <%= form.label :disponibility %>
  <%= form.text_field :disponibility %>
</div>


<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/products/_product_modal.html.erb
<%# <div id="product-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div>
         <%= @typ.content%>
<%# <%=image_tag (@arti.image_url)%>
<%# <%=@arti.id%>

      <%# </div>
    </div>
  </div>
</div> %>

app/views/products/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', product_path %>

app/views/products/index.html.erb
<!-- <div class="container">
  <h2>Vrac</h2>
  <div class="row">
    <%@product.each do |product|%>
      <% if product.type.content == "Vrac" %>
          <div class="col-lg-4">
            <%= image_tag (product.article.image_url), class:"rounded-circle tailimgmanager"%>
            <h2><%= product.type.content%></h2>
            <%= link_to 'View post', product_path(product.id) %> /
            <%= link_to 'View Article', article_path(product.article_id) %> </br>

            <% if current_user %>
            <% pre_like = product.likes.find { |like| like.user_id == current_user.id} %>
            <% if pre_like %>
            <%= link_to '', product_like_path(product, pre_like), method: :delete, class:"fas fa-heart zomm" %>
            <% else %>
            <%= link_to'', product_likes_path(product), method: :post, class:"far fa-heart zomm" %>
            <% end %>
            <% end %>
            <div class="d-flex">
              <div>
                <p class="btn btn-outline like-view"><%= product.likes.count %> <i class="fas fa-heart"></i></p>
              </div>
              <div>
                <%= button_to line_items_path(product_id: product.id),class:"btn btn-outline-primary" do %>
                <i class="fas fa-shopping-basket"></i>
                <% end %>
              </div>
            </div>
          </div>
      <% end %>
    <% end %>
  </div>

<br>
<hr>
<br>
    <h2>Doypack</h2>
   <div class="row">
     <%@product.each do |product|%>
     <% if product.type.content == "Doypack" %>
     <div class="col-lg-4">
       <%= image_tag (product.article.image_url), class:"rounded-circle tailimgmanager"%>
       <h2><%= product.type.content%></h2>
       <%= link_to 'View post', product_path(product.id) %> /
       <%= link_to 'View Article', article_path(product.article_id) %> </br>

       <% if current_user %>
       <% pre_like = product.likes.find { |like| like.user_id == current_user.id} %>
       <% if pre_like %>
       <%= link_to '', product_like_path(product, pre_like), method: :delete, class:"fas fa-heart zomm" %>
       <% else %>
       <%= link_to'', product_likes_path(product), method: :post, class:"far fa-heart zomm" %>
       <% end %>
       <% end %>
      <div class="d-flex">
        <div>
          <p class="btn btn-outline like-view"><%= product.likes.count %> <i class="fas fa-heart"></i></p>
        </div>
        <div>
          <%= button_to line_items_path(product_id: product.id),class:"btn btn-outline-primary" do %>
          <i class="fas fa-shopping-basket"></i>
          <% end %>
        </div>
      </div>
       
       


     </div>
     <% end %>
     <% end %>
   </div>
     <hr>
     <%= link_to "retour page d'accueil ", root_path %>
     <hr>
</div> -->

<section>
  <div>
    <h2 class="center">Nos produits phare </h2>
  </div>
  <div class="container-img">
    <%@product.each do |product|%>
    <div class="cardimg">
      <div class="imagbx">
        <%= image_tag (product.article.image_url), class:"imgtail" %>
      </div>
      <div class="details">
        <h2><%= product.type.content%></h2>
       
        (<%= product.likes.count %>)
         <% if current_user %>
         <% pre_like = product.likes.find { |like| like.user_id == current_user.id} %>

         <% if pre_like %>
         <%= link_to '', product_like_path(product, pre_like), method: :delete, class:"far fa-thumbs-down zomm" %>
         <% else %>
         <%= link_to'', product_likes_path(product), method: :post, class:"far fa-thumbs-up zomm" %>
         <% end %>
         <% else %>
          <i class="far fa-thumbs-up"></i>
         <% end %>
        

        <p class="listprod"><%=product.article.title%></p>
        <%if product.type.content == "Vrac" %>
        <p class="listprod"><%= product.price%> euros/kg</p>
        <%else%>
        <p class="listprod"><%= product.price%> euros/unité</p>
        <%end%>
          <%if  product.disponibility == true %>
          <p class="listprod listcol">Disponible immédiatement </p>
          <%else%>
          <p class="listprod listcol">Non disponible pour le moment </p>
          <%end%>

          <div class="shopcart">
            <%= button_to line_items_path(product_id: product.id),class:"btn btn-warning" do %>
            <i class="fas fa-shopping-basket"></i>
            <% end %>
            <%= link_to 'View Article', article_path(product.article_id) %> </br>

          </div>
      </div>
    </div>
    <% end %>
  </div>  
</section>
 <hr>
 <%= link_to "retour page d'accueil ", root_path %>
 <hr>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">
  <h2><%= @arti.title%></br></h2>
  <div class="d-flex">
    <div class="pic-product-containt">
      <% if @arti.image_url == nil %>
        <%= image_tag ("fond.jpg"), class:"product-pic"%>
      <%else%>
        <%= image_tag (@arti.image_url), class:"product-pic" %>
      <%end%>
    </div>
    
    <div>
      <%=@arti.id %>/
      <%=@product.price %>
      <% if current_manager %>
          <%= link_to 'Edit', edit_product_path(@product) %> |
      <% end %>

      <p><%= @product.likes.count %> <%= (@product.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    </div>
  </div>

<hr>
  <%= link_to "retour ", products_path %>
  <hr>
  <%= link_to "retour page d'accueil ", root_path %>
  <hr>
</div>

app/views/products/show.js.erb
<%# $('#post-content').html("<%= j render 'product_modal', product: @product %>
<%# $('#product-modal').modal('show'); %> 